### ISSUE TITLE
In infiniteSum() document that if alternate = 0 then it is assumed that the sign of the first term is positive

### ISSUE THREAD

**Issue by paulnorthrop** [GuidoAMoreira/sumR#3]
Thank you for creating the package, Guido.  I am finding it very useful.  

Am I correct in thinking that if alternate = 0 in a call to infiniteSum() then we should ensure that the first term evaluated in logFunction is positive? 

The function logFunction() returns the log of the absolute value of a_n but there is no argument to set the sign of the first term when the series is not alternating.  Based on examples that I have used it seems that the code is based on the first term is positive.  This makes sense but it would be helpful for this to be documented.  Please accept my apologies if this is already documented and I have missed it.

**Comment by GuidoAMoreira** [comment]
Hello, Paul, thank you for your comment.

Perhaps the documentation is not clear. The case where `alternate = 0` is the very case for a non-alternating series. The case where `alternate = 1` is the case where the first term of a_n is positive and `alternate = -1` is the case where it is negative.

I'll think of a way to improve the documentation based on your comment.

Cheers!

**Comment by paulnorthrop** [comment]
Yes, I think that it would help to note that in the `alternate = 0` case all terms must be positive.  Thank you!
